### ISSUE TITLE
container doesn't work on singularity v3.0

### ISSUE THREAD

**Issue by soichih** [Ngoyal95/kwyk_neuronet#8]
I am trying to run the docker container with tag "neuronets/kwyk:latest-gpu". It *works fine* on singularity v2 sites, but when I run it on singularity v3 sites (like PSC bridges), I ran into the following error message.

```
[shayashi@login005 ~]$ singularity run -B $(pwd):/data -W /data --nv docker://neuronets/kwyk:latest-gpu --help
INFO:    Could not find any NVIDIA binaries on this host!
Traceback (most recent call last):
  File "/usr/local/bin/kwyk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'kwyk' distribution was not found and is required by the application

```

I think this is probably a bug with singularity,.. just FYI

**Comment by soichih** [comment]
I just tried running it on singularity v3.4.1, and it worked fine. So it looks like this is caused by *old* version of singularity v3. I will see if I can ask the admin to upgrade singularity on bridges.
